baseURL = "/"
languageCode = "en-us"
title = "My Site"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 3
